# You can remove the version field if you see warnings with your Compose version.
# version: '3.8'

services:
  web:
    image: lostfound_web:latest   # Replace build: . with your built image reference
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    deploy:
      replicas: 3

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lost_found_db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
